// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu7ILppzVTV8L4fxDKQAiJAoSuv6qwOJk',
    appId: '1:736442778132:web:0b4b9c0f683e4c8b419d01',
    messagingSenderId: '736442778132',
    projectId: 'ecart-app-d2148',
    authDomain: 'ecart-app-d2148.firebaseapp.com',
    storageBucket: 'ecart-app-d2148.appspot.com',
    measurementId: 'G-J02NLSG3HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtqCtX5mmPntUtpYYBa1Fh8bjIS44sIY',
    appId: '1:736442778132:android:8a38386ae60f8aae419d01',
    messagingSenderId: '736442778132',
    projectId: 'ecart-app-d2148',
    storageBucket: 'ecart-app-d2148.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpCGGuDpZ7Fx55-QICIDhRbDnQwpGYJw',
    appId: '1:736442778132:ios:1510e99898817445419d01',
    messagingSenderId: '736442778132',
    projectId: 'ecart-app-d2148',
    storageBucket: 'ecart-app-d2148.appspot.com',
    iosBundleId: 'com.example.eCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpCGGuDpZ7Fx55-QICIDhRbDnQwpGYJw',
    appId: '1:736442778132:ios:16ad92dfb227eaa3419d01',
    messagingSenderId: '736442778132',
    projectId: 'ecart-app-d2148',
    storageBucket: 'ecart-app-d2148.appspot.com',
    iosBundleId: 'com.example.eCart.RunnerTests',
  );
}
